# Generated by Django 5.2.17 on 2026-10-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('es_demo', models.BooleanField(default=False, verbose_name='dato de demostración')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('es_demo', models.BooleanField(default=False, verbose_name='dato de demostración')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='organizacion.area', verbose_name='área')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('es_demo', models.BooleanField(default=False, verbose_name='dato de demostración')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['codigo'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo__regex', '^\\s*$'), _negated=True), name='ck_organizacion_empresa_codigo_no_vacio'), models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='ck_organizacion_empresa_nombre_no_vacio')],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='organizacion.empresa', verbose_name='empresa'),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('es_demo', models.BooleanField(default=False, verbose_name='dato de demostración')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='organizacion.departamento', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('es_demo', models.BooleanField(default=False, verbose_name='dato de demostración')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='organizacion.seccion', verbose_name='sección')),
            ],
            options={
                'verbose_name': 'puesto',
                'verbose_name_plural': 'puestos',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('area', 'codigo'), name='uq_organizacion_departamento_padre_codigo', violation_error_message='Ya existe un departamento con ese código en el área.'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.CheckConstraint(condition=models.Q(('codigo__regex', '^\\s*$'), _negated=True), name='ck_organizacion_departamento_codigo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='ck_organizacion_departamento_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_organizacion_area_padre_codigo', violation_error_message='Ya existe un área con ese código en la empresa.'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.CheckConstraint(condition=models.Q(('codigo__regex', '^\\s*$'), _negated=True), name='ck_organizacion_area_codigo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='ck_organizacion_area_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.UniqueConstraint(fields=('departamento', 'codigo'), name='uq_organizacion_seccion_padre_codigo', violation_error_message='Ya existe una sección con ese código en el departamento.'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.CheckConstraint(condition=models.Q(('codigo__regex', '^\\s*$'), _negated=True), name='ck_organizacion_seccion_codigo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='ck_organizacion_seccion_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.UniqueConstraint(fields=('seccion', 'codigo'), name='uq_organizacion_puesto_padre_codigo', violation_error_message='Ya existe un puesto con ese código en la sección.'),
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.CheckConstraint(condition=models.Q(('codigo__regex', '^\\s*$'), _negated=True), name='ck_organizacion_puesto_codigo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='ck_organizacion_puesto_nombre_no_vacio'),
        ),
    ]
