# Generated by Django 5.2.17 on 2026-10-02 18:42

import cuentas.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=10, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='usuario_username_unico_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='usuario_email_unico_ci'), models.CheckConstraint(condition=models.Q(('rol__in', ['ADMIN', 'CONSULTA'])), name='usuario_rol_valido'), models.CheckConstraint(condition=models.Q(('username__regex', '^\\s*$'), _negated=True), name='usuario_username_no_vacio'), models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='usuario_nombre_no_vacio')],
            },
            managers=[
                ('objects', cuentas.models.UsuarioManager()),
            ],
        ),
    ]
