# Generated by Django 5.2.17 on 2026-10-03 02:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_en', models.DateTimeField(auto_now_add=True, verbose_name='iniciada en')),
                ('finalizada_en', models.DateTimeField(blank=True, null=True, verbose_name='finalizada en')),
                ('archivo_nombre', models.CharField(max_length=255, verbose_name='archivo')),
                ('archivo_sha256', models.CharField(max_length=64, verbose_name='SHA-256 del archivo')),
                ('hoja', models.CharField(default='Servicios Externos', max_length=100, verbose_name='hoja')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida')], default='EN_CURSO', max_length=10, verbose_name='estado')),
                ('creados', models.PositiveIntegerField(default=0, verbose_name='creados')),
                ('actualizados', models.PositiveIntegerField(default=0, verbose_name='actualizados')),
                ('sin_cambios', models.PositiveIntegerField(default=0, verbose_name='sin cambios')),
                ('omitidos', models.PositiveIntegerField(default=0, verbose_name='omitidos')),
                ('observados', models.PositiveIntegerField(default=0, verbose_name='observados')),
                ('total_n1', models.PositiveIntegerField(blank=True, null=True, verbose_name='códigos de nivel 1')),
                ('total_n2', models.PositiveIntegerField(blank=True, null=True, verbose_name='códigos de nivel 2')),
                ('detalle_conteos', models.JSONField(blank=True, default=dict, verbose_name='detalle de conteos')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='mensaje de error')),
                ('ejecutada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to=settings.AUTH_USER_MODEL, verbose_name='ejecutada por')),
            ],
            options={
                'verbose_name': 'ejecución de importación',
                'verbose_name_plural': 'ejecuciones de importación',
                'ordering': ['-iniciada_en', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MapeoCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('ETIQUETA_CLASE', 'Etiqueta de clase'), ('ETIQUETA_CRITICIDAD', 'Etiqueta de criticidad'), ('ETIQUETA_TIPO', 'Etiqueta de tipo'), ('NOMBRE_N1', 'Nombre de nivel 1'), ('NOMBRE_N2', 'Nombre de nivel 2'), ('CODIGO_N2', 'Código de nivel 2')], max_length=30, verbose_name='ámbito')),
                ('valor_original', models.TextField(verbose_name='valor original')),
                ('valor_corregido', models.TextField(verbose_name='valor corregido')),
                ('celda_origen', models.CharField(blank=True, max_length=20, null=True, verbose_name='celda de origen')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'mapeo de corrección',
                'verbose_name_plural': 'mapeos de corrección',
                'constraints': [models.UniqueConstraint(fields=('ambito', 'valor_original'), name='uq_mapeocorreccion_ambito_valor'), models.CheckConstraint(condition=models.Q(('ambito__in', ['ETIQUETA_CLASE', 'ETIQUETA_CRITICIDAD', 'ETIQUETA_TIPO', 'NOMBRE_N1', 'NOMBRE_N2', 'CODIGO_N2'])), name='ck_mapeocorreccion_ambito'), models.CheckConstraint(condition=models.Q(('valor_corregido', models.F('valor_original')), _negated=True), name='ck_mapeocorreccion_cambia_valor')],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONFLICTO_NOMBRE_N1', 'Conflicto de nombre de nivel 1'), ('FILA_SIN_CODIGO', 'Fila sin código'), ('PADRE_POR_PREFIJO', 'Nivel 1 asignado por prefijo'), ('ATRIBUTOS_AUSENTES', 'Atributos ausentes'), ('CODIGO_FORMATO_NO_ESTANDAR', 'Código con formato no estándar'), ('CORRECCION_APLICADA', 'Corrección aplicada'), ('POSIBLE_ERROR_ESCRITURA', 'Posible error de escritura'), ('VALOR_NO_RECONOCIDO', 'Valor no reconocido'), ('TEXTO_CON_FORMA_DE_INSTRUCCION', 'Texto con forma de instrucción'), ('ESPACIOS_EN_TEXTO', 'Espacios en el texto'), ('AUSENCIA_EN_CONTINUACION', 'Ausencia en filas de continuación'), ('CONTROL_CONTEO', 'Control de conteo')], max_length=40, verbose_name='tipo')),
                ('severidad', models.CharField(choices=[('INFO', 'Información'), ('ADVERTENCIA', 'Advertencia'), ('ERROR', 'Error')], default='ADVERTENCIA', max_length=12, verbose_name='severidad')),
                ('codigo_afectado', models.CharField(blank=True, max_length=20, null=True, verbose_name='código afectado')),
                ('filas', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='filas')),
                ('celdas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='celdas')),
                ('detalle', models.TextField(verbose_name='detalle')),
                ('valores_conflicto', models.JSONField(blank=True, null=True, verbose_name='valores en conflicto')),
                ('regla_aplicada', models.TextField(blank=True, null=True, verbose_name='regla aplicada')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='importacion.ejecucion')),
                ('servicio_nivel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='catalogo.servicionivel1')),
                ('servicio_nivel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='catalogo.servicionivel2')),
            ],
            options={
                'verbose_name': 'observación de importación',
                'verbose_name_plural': 'observaciones de importación',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrigenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja', models.CharField(max_length=100, verbose_name='hoja')),
                ('filas', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='filas')),
                ('rangos_combinados', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='rangos combinados')),
                ('valores_originales', models.JSONField(verbose_name='valores originales')),
                ('transformaciones', models.JSONField(blank=True, default=list, verbose_name='transformaciones')),
                ('ultima_accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('SIN_CAMBIOS', 'Sin cambios')], max_length=12, verbose_name='última acción')),
                ('primera_ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origenes_creados', to='importacion.ejecucion')),
                ('servicio_nivel1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origen', to='catalogo.servicionivel1')),
                ('servicio_nivel2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origen', to='catalogo.servicionivel2')),
                ('ultima_ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origenes_actualizados', to='importacion.ejecucion')),
            ],
            options={
                'verbose_name': 'origen de servicio',
                'verbose_name_plural': 'orígenes de servicio',
            },
        ),
        migrations.AddConstraint(
            model_name='ejecucion',
            constraint=models.CheckConstraint(condition=models.Q(('finalizada_en__isnull', True), ('finalizada_en__gte', models.F('iniciada_en')), _connector='OR'), name='ck_ejecucion_finalizada_tras_inicio'),
        ),
        migrations.AddConstraint(
            model_name='ejecucion',
            constraint=models.CheckConstraint(condition=models.Q(('archivo_sha256__regex', '^[0-9a-f]{64}$')), name='ck_ejecucion_sha256'),
        ),
        migrations.AddConstraint(
            model_name='ejecucion',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['EN_CURSO', 'EXITOSA', 'FALLIDA'])), name='ck_ejecucion_estado'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['CONFLICTO_NOMBRE_N1', 'FILA_SIN_CODIGO', 'PADRE_POR_PREFIJO', 'ATRIBUTOS_AUSENTES', 'CODIGO_FORMATO_NO_ESTANDAR', 'CORRECCION_APLICADA', 'POSIBLE_ERROR_ESCRITURA', 'VALOR_NO_RECONOCIDO', 'TEXTO_CON_FORMA_DE_INSTRUCCION', 'ESPACIOS_EN_TEXTO', 'AUSENCIA_EN_CONTINUACION', 'CONTROL_CONTEO'])), name='ck_observacion_tipo'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(condition=models.Q(('severidad__in', ['INFO', 'ADVERTENCIA', 'ERROR'])), name='ck_observacion_severidad'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(condition=models.Q(('filas__len__gte', 1)), name='ck_observacion_filas'),
        ),
        migrations.AddConstraint(
            model_name='origenservicio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('servicio_nivel1__isnull', False), ('servicio_nivel2__isnull', True)), models.Q(('servicio_nivel1__isnull', True), ('servicio_nivel2__isnull', False)), _connector='OR'), name='ck_origen_un_servicio'),
        ),
        migrations.AddConstraint(
            model_name='origenservicio',
            constraint=models.CheckConstraint(condition=models.Q(('filas__len__gte', 1)), name='ck_origen_filas'),
        ),
        migrations.AddConstraint(
            model_name='origenservicio',
            constraint=models.CheckConstraint(condition=models.Q(('ultima_accion__in', ['CREADO', 'ACTUALIZADO', 'SIN_CAMBIOS'])), name='ck_origen_ultima_accion'),
        ),
    ]
