# Generated by Django 5.2.17 on 2026-10-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('importacion', '0002_mapeo_correccion_inicial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='observacion',
            name='ck_observacion_tipo',
        ),
        migrations.AddField(
            model_name='observacion',
            name='ejecuciones',
            field=models.ManyToManyField(blank=True, related_name='observaciones_emitidas', to='importacion.ejecucion', verbose_name='ejecuciones'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='huella',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='huella'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='ejecucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='importacion.ejecucion', verbose_name='primera ejecución'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='tipo',
            field=models.CharField(choices=[('CONFLICTO_NOMBRE_N1', 'Conflicto de nombre de nivel 1'), ('FILA_SIN_CODIGO', 'Fila sin código'), ('PADRE_POR_PREFIJO', 'Nivel 1 asignado por prefijo'), ('ATRIBUTOS_AUSENTES', 'Atributos ausentes'), ('CODIGO_FORMATO_NO_ESTANDAR', 'Código con formato no estándar'), ('CORRECCION_APLICADA', 'Corrección aplicada'), ('POSIBLE_ERROR_ESCRITURA', 'Posible error de escritura'), ('VALOR_NO_RECONOCIDO', 'Valor no reconocido'), ('TEXTO_CON_FORMA_DE_INSTRUCCION', 'Texto con forma de instrucción'), ('ESPACIOS_EN_TEXTO', 'Espacios en el texto'), ('AUSENCIA_EN_CONTINUACION', 'Ausencia en filas de continuación'), ('CONTROL_CONTEO', 'Control de conteo'), ('CONFLICTO_ATRIBUTOS', 'Conflicto de atributos del servicio')], max_length=40, verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['CONFLICTO_NOMBRE_N1', 'FILA_SIN_CODIGO', 'PADRE_POR_PREFIJO', 'ATRIBUTOS_AUSENTES', 'CODIGO_FORMATO_NO_ESTANDAR', 'CORRECCION_APLICADA', 'POSIBLE_ERROR_ESCRITURA', 'VALOR_NO_RECONOCIDO', 'TEXTO_CON_FORMA_DE_INSTRUCCION', 'ESPACIOS_EN_TEXTO', 'AUSENCIA_EN_CONTINUACION', 'CONTROL_CONTEO', 'CONFLICTO_ATRIBUTOS'])), name='ck_observacion_tipo'),
        ),
    ]
