# Generated by Django 5.2.17 on 2026-10-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('importacion', '0003_observacion_deduplicada'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='observacion',
            name='ck_observacion_tipo',
        ),
        migrations.RemoveConstraint(
            model_name='origenservicio',
            name='ck_origen_ultima_accion',
        ),
        migrations.AlterField(
            model_name='observacion',
            name='tipo',
            field=models.CharField(choices=[('CONFLICTO_NOMBRE_N1', 'Conflicto de nombre de nivel 1'), ('FILA_SIN_CODIGO', 'Fila sin código'), ('PADRE_POR_PREFIJO', 'Nivel 1 asignado por prefijo'), ('ATRIBUTOS_AUSENTES', 'Atributos ausentes'), ('CODIGO_FORMATO_NO_ESTANDAR', 'Código con formato no estándar'), ('CORRECCION_APLICADA', 'Corrección aplicada'), ('POSIBLE_ERROR_ESCRITURA', 'Posible error de escritura'), ('VALOR_NO_RECONOCIDO', 'Valor no reconocido'), ('TEXTO_CON_FORMA_DE_INSTRUCCION', 'Texto con forma de instrucción'), ('ESPACIOS_EN_TEXTO', 'Espacios en el texto'), ('AUSENCIA_EN_CONTINUACION', 'Ausencia en filas de continuación'), ('CONTROL_CONTEO', 'Control de conteo'), ('CONFLICTO_ATRIBUTOS', 'Conflicto de atributos del servicio'), ('REFERENCIA_INACTIVA', 'Referencia inactiva')], max_length=40, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='origenservicio',
            name='ultima_accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('SIN_CAMBIOS', 'Sin cambios'), ('OBSERVADO', 'Observado (sin cambios aplicados)')], max_length=12, verbose_name='última acción'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['CONFLICTO_NOMBRE_N1', 'FILA_SIN_CODIGO', 'PADRE_POR_PREFIJO', 'ATRIBUTOS_AUSENTES', 'CODIGO_FORMATO_NO_ESTANDAR', 'CORRECCION_APLICADA', 'POSIBLE_ERROR_ESCRITURA', 'VALOR_NO_RECONOCIDO', 'TEXTO_CON_FORMA_DE_INSTRUCCION', 'ESPACIOS_EN_TEXTO', 'AUSENCIA_EN_CONTINUACION', 'CONTROL_CONTEO', 'CONFLICTO_ATRIBUTOS', 'REFERENCIA_INACTIVA'])), name='ck_observacion_tipo'),
        ),
        migrations.AddConstraint(
            model_name='origenservicio',
            constraint=models.CheckConstraint(condition=models.Q(('ultima_accion__in', ['CREADO', 'ACTUALIZADO', 'SIN_CAMBIOS', 'OBSERVADO'])), name='ck_origen_ultima_accion'),
        ),
    ]
