# Generated by Django 5.2.17 on 2026-10-03 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(error_messages={'unique': 'Ya existe un valor con ese código en este catálogo.'}, max_length=30, unique=True, verbose_name='código')),
                ('etiqueta_original', models.CharField(error_messages={'unique': 'Ya existe un valor con esa etiqueta en este catálogo.'}, help_text='Texto exacto de la lista del Excel o el registrado al crear el valor.', max_length=100, unique=True, verbose_name='etiqueta original')),
                ('etiqueta_mostrada', models.CharField(max_length=100, verbose_name='etiqueta')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('fila_origen', models.PositiveIntegerField(blank=True, null=True, verbose_name='fila de origen')),
            ],
            options={
                'verbose_name': 'clase de servicio',
                'verbose_name_plural': 'clases de servicio',
                'ordering': ['orden', 'codigo'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_]+$')), name='ck_catalogo_claseservicio_codigo'), models.CheckConstraint(condition=models.Q(('etiqueta_original__regex', '^\\s*$'), _negated=True), name='ck_catalogo_claseservicio_etiqueta_original_no_vacio'), models.CheckConstraint(condition=models.Q(('etiqueta_mostrada__regex', '^\\s*$'), _negated=True), name='ck_catalogo_claseservicio_etiqueta_mostrada_no_vacio')],
            },
        ),
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(error_messages={'unique': 'Ya existe un valor con ese código en este catálogo.'}, max_length=30, unique=True, verbose_name='código')),
                ('etiqueta_original', models.CharField(error_messages={'unique': 'Ya existe un valor con esa etiqueta en este catálogo.'}, help_text='Texto exacto de la lista del Excel o el registrado al crear el valor.', max_length=100, unique=True, verbose_name='etiqueta original')),
                ('etiqueta_mostrada', models.CharField(max_length=100, verbose_name='etiqueta')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('fila_origen', models.PositiveIntegerField(blank=True, null=True, verbose_name='fila de origen')),
            ],
            options={
                'verbose_name': 'criticidad',
                'verbose_name_plural': 'criticidades',
                'ordering': ['orden', 'codigo'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_]+$')), name='ck_catalogo_criticidad_codigo'), models.CheckConstraint(condition=models.Q(('etiqueta_original__regex', '^\\s*$'), _negated=True), name='ck_catalogo_criticidad_etiqueta_original_no_vacio'), models.CheckConstraint(condition=models.Q(('etiqueta_mostrada__regex', '^\\s*$'), _negated=True), name='ck_catalogo_criticidad_etiqueta_mostrada_no_vacio')],
            },
        ),
        migrations.CreateModel(
            name='ServicioNivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(error_messages={'unique': 'Ya existe un servicio de nivel 1 con ese código.'}, max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('estado_revision', models.CharField(choices=[('SIN_OBSERVACIONES', 'Sin observaciones'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('REVISADO', 'Revisado')], default='SIN_OBSERVACIONES', max_length=20, verbose_name='estado de revisión')),
            ],
            options={
                'verbose_name': 'servicio de nivel 1',
                'verbose_name_plural': 'servicios de nivel 1',
                'ordering': ['codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo__regex', '^\\s*$'), _negated=True), name='ck_catalogo_servicionivel1_codigo_no_vacio'), models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='ck_catalogo_servicionivel1_nombre_no_vacio'), models.CheckConstraint(condition=models.Q(('estado_revision__in', ['SIN_OBSERVACIONES', 'PENDIENTE_REVISION', 'REVISADO'])), name='ck_catalogo_servicionivel1_estado_revision')],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(error_messages={'unique': 'Ya existe un valor con ese código en este catálogo.'}, max_length=30, unique=True, verbose_name='código')),
                ('etiqueta_original', models.CharField(error_messages={'unique': 'Ya existe un valor con esa etiqueta en este catálogo.'}, help_text='Texto exacto de la lista del Excel o el registrado al crear el valor.', max_length=100, unique=True, verbose_name='etiqueta original')),
                ('etiqueta_mostrada', models.CharField(max_length=100, verbose_name='etiqueta')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('fila_origen', models.PositiveIntegerField(blank=True, null=True, verbose_name='fila de origen')),
            ],
            options={
                'verbose_name': 'tipo de servicio',
                'verbose_name_plural': 'tipos de servicio',
                'ordering': ['orden', 'codigo'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_]+$')), name='ck_catalogo_tiposervicio_codigo'), models.CheckConstraint(condition=models.Q(('etiqueta_original__regex', '^\\s*$'), _negated=True), name='ck_catalogo_tiposervicio_etiqueta_original_no_vacio'), models.CheckConstraint(condition=models.Q(('etiqueta_mostrada__regex', '^\\s*$'), _negated=True), name='ck_catalogo_tiposervicio_etiqueta_mostrada_no_vacio')],
            },
        ),
        migrations.CreateModel(
            name='ServicioNivel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('codigo_original', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='código original')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo_excel', models.TextField(blank=True, null=True, verbose_name='ACTIVO (Excel)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('metrica', models.CharField(blank=True, max_length=200, null=True, verbose_name='métrica')),
                ('minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='mínimo')),
                ('maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='máximo')),
                ('estado_revision', models.CharField(choices=[('SIN_OBSERVACIONES', 'Sin observaciones'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('REVISADO', 'Revisado')], default='SIN_OBSERVACIONES', max_length=20, verbose_name='estado de revisión')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo.claseservicio', verbose_name='clase de servicio')),
                ('criticidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo.criticidad', verbose_name='criticidad')),
                ('nivel1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_nivel2', to='catalogo.servicionivel1', verbose_name='servicio de nivel 1')),
                ('seccion_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_asignados', to='organizacion.seccion', verbose_name='sección responsable')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='usuario responsable')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo.tiposervicio', verbose_name='tipo de servicio')),
            ],
            options={
                'verbose_name': 'servicio de nivel 2',
                'verbose_name_plural': 'servicios de nivel 2',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['activo'], name='ix_n2_activo'), models.Index(fields=['activo_excel'], name='ix_n2_activo_excel')],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='uq_n2_codigo', violation_error_message='Ya existe un servicio de nivel 2 con ese código.'), models.UniqueConstraint(condition=models.Q(('codigo_original__isnull', False)), fields=('codigo_original',), name='uq_n2_codigo_original'), models.CheckConstraint(condition=models.Q(('minimo__isnull', True), ('maximo__isnull', True), ('minimo__lte', models.F('maximo')), _connector='OR'), name='ck_n2_minimo_le_maximo', violation_error_message='El mínimo no puede ser mayor que el máximo.'), models.CheckConstraint(condition=models.Q(('usuario_responsable__isnull', True), ('seccion_responsable__isnull', False), _connector='OR'), name='ck_n2_usuario_requiere_seccion', violation_error_message='Un usuario responsable requiere una sección responsable.'), models.CheckConstraint(condition=models.Q(('activo_excel__isnull', True), models.Q(('activo_excel', ''), _negated=True), _connector='OR'), name='ck_n2_activo_excel_no_vacio'), models.CheckConstraint(condition=models.Q(('codigo__regex', '^\\s*$'), _negated=True), name='ck_catalogo_servicionivel2_codigo_no_vacio'), models.CheckConstraint(condition=models.Q(('nombre__regex', '^\\s*$'), _negated=True), name='ck_catalogo_servicionivel2_nombre_no_vacio'), models.CheckConstraint(condition=models.Q(('estado_revision__in', ['SIN_OBSERVACIONES', 'PENDIENTE_REVISION', 'REVISADO'])), name='ck_catalogo_servicionivel2_estado_revision')],
            },
        ),
    ]
