target-version = "py312"
line-length = 100
extend-exclude = ["*/migrations/*", "staticfiles"]

[lint]
select = ["E", "F", "W", "I", "B", "UP", "DJ"]

[lint.isort]
known-first-party = ["config", "cuentas", "organizacion", "catalogo", "importacion"]
